version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dvdrental-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dvdrental
    ports:
      - "5432:5432"
    volumes:
      - dvdrental_data:/var/lib/postgresql/data
      - ./dvd_dat:/data

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: discs-of-fame-app
    volumes:
      - .:/workspace
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dvdrental

volumes:
  dvdrental_data: