name: Registro de actividad

# Se ejecuta en push o pull request en cualquier rama
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:  # Permite ejecutar manualmente desde Actions

jobs:
  historial:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Mostrar historial de commits
        run: |
          echo "========== Historial de actividad =========="
          echo "Últimos 10 commits en este branch:"
          git log -10 --pretty=format:"%h - %an - %s - %ad - (branch: %D)" --date=short
          echo "==========================================="

